### PR TITLE
refactor(client): Cleanup and unification.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
- Alphabetization in several places.
- Simplify required option checks.
- experiment.js name unification with experiment-mixin.js:
  - isOptedInTo->isInExperiment
  - isGroup->isInExperimentGroup
- document BaseExperiment.createSaveStateDelegate

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Travis needs a tire kick, since it's on your repo @vladikoff, I can't trigger a new build unless I change a file.

**Comment by vladikoff** [comment]
> Travis needs a tire kick, since it's on your repo @vladikoff, I can't trigger a new build unless I change a file.

Next time just `git --amend` and push again and it should restart the build

**Comment by vladikoff** [comment]
@shane-tomlinson could you rebase this? Let me know if you don't have time and then I will manually merge it

**Comment by shane-tomlinson** [comment]
@vladikoff - on it.

**Pull request merged**
